function paper = loadpaper(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RMJOURNALPAPER = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RMJOURNALPAPER = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  rmjournalpaper = importfile("rm_journal_paper.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2023/01/09 10:06:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 33, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "ID", "Title_JP", "Title_EN", "Author_JP", "Author_EN", "Role", "VarName10", "VarName11", "VarName12", "VarName13", "DateRaw", "Journal_JP", "Journal_EN", "Vol", "No", "Page_ST", "Page_ED", "Language", "Review", "Invited", "Type", "VarName25", "International_Work", "DOI", "ISSN", "eISSN", "URL", "URL2", "VarName32", "Public"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "string", "string", "string", "string", "string", "categorical", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "string", "string", "string", "string", "string", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ID", "Title_JP", "Title_EN", "Author_JP", "Author_EN", "VarName10", "VarName11", "DOI", "ISSN", "eISSN", "URL"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "ID", "Title_JP", "Title_EN", "Author_JP", "Author_EN", "Role", "VarName10", "VarName11", "VarName12", "VarName13", "Journal_JP", "Journal_EN", "Language", "Review", "Invited", "Type", "VarName25", "International_Work", "DOI", "ISSN", "eISSN", "URL", "VarName32", "Public"], "EmptyFieldRule", "auto");

% Import the data
paper = readtable(filename, opts);

% shape dates
for k = 1:size(paper,1)
    if strlength(string(paper.DateRaw(k))) == 4
        paper.Date(k) = datetime(string(paper.DateRaw(k)),"InputFormat","yyyy","Locale","ja_JP");
    elseif strlength(string(paper.DateRaw(k))) == 6
        paper.Date(k) = datetime(string(paper.DateRaw(k)),"InputFormat","yyyyMM","Locale","ja_JP");
    elseif strlength(string(paper.DateRaw(k))) == 7
        paper.Date(k) = datetime(string(paper.DateRaw(k)),"InputFormat","yyyy-MM","Locale","ja_JP");
    elseif strlength(string(paper.DateRaw(k))) == 8
        paper.Date(k) = datetime(string(paper.DateRaw(k)),"InputFormat","yyyyMMdd","Locale","ja_JP");
    else
        error("Error in date format");
    end
end

paper.Author_JP=strrep(strrep(paper.Author_JP,"[",""),"]","");
paper.Author_EN=strrep(strrep(paper.Author_EN,"[",""),"]","");
% year = zeros(size(paper,1),1);

end

