function jointResearch = loadjoint(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  JOINTRESEARCH = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  JOINTRESEARCH = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  JOINTRESEARCH = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  jointResearch = importfile("jointResearch.xlsx", "Sheet1", [2, 9]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2022/05/01 15:48:48

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 1000];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Company", "Title", "StartDate", "EndDate", "Amont_total", "Note"];
opts.VariableTypes = ["string", "string", "datetime", "datetime", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Company", "Title", "Note"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Company", "Title", "Note"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "StartDate", "InputFormat", "");
opts = setvaropts(opts, "EndDate", "InputFormat", "");

% Import the data
jointResearch = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    jointResearch = [jointResearch; tb]; %#ok<AGROW>
end

jointResearch = jointResearch(~strcmp(jointResearch.Company,""),:);

end