function rmresearchprojects = loadfund(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RMRESEARCHPROJECTS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  RMRESEARCHPROJECTS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  rmresearchprojects = importfile("G:\My Drive\Job\Achievement\data\rm_research_projects.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2023/01/09 12:01:29

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 30, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "ID", "Title_JP", "Title_EN", "Name_JP", "Name_EN", "Institute_JP", "Institute_EN", "FundName_JP", "FundName_EN", "VarName13", "VarName14", "VarName15", "VarName16", "From", "To", "MemberType", "Budget_all", "Budget_direct", "Budget_indirect", "VarName23", "VarName24", "Type", "VarName26", "ProjectNumber", "URL", "VarName29", "VarName30"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "categorical", "double", "double", "double", "string", "string", "categorical", "string", "string", "string", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ID", "Title_JP", "Title_EN", "Institute_JP", "Institute_EN", "FundName_JP", "FundName_EN", "VarName13", "VarName14", "VarName15", "VarName16", "VarName23", "VarName24", "VarName26", "ProjectNumber", "URL"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "ID", "Title_JP", "Title_EN", "Name_JP", "Name_EN", "Institute_JP", "Institute_EN", "FundName_JP", "FundName_EN", "VarName13", "VarName14", "VarName15", "VarName16", "MemberType", "VarName23", "VarName24", "Type", "VarName26", "ProjectNumber", "URL", "VarName29", "VarName30"], "EmptyFieldRule", "auto");

% Import the data
rmresearchprojects = readtable(filename, opts);

rmresearchprojects.From = datetime(string(rmresearchprojects.From),"InputFormat","yyyyMMdd");
rmresearchprojects.To = datetime(string(rmresearchprojects.To),"InputFormat","yyyyMMdd");

% for k = 1:size(rmresearchprojects,1)
%     if strlength(string(rmresearchprojects.DateRaw(k))) == 4
%         rmresearchprojects.Date(k) = datetime(string(rmresearchprojects.DateRaw(k)),"InputFormat","yyyy","Locale","ja_JP");
%     elseif strlength(string(rmresearchprojects.DateRaw(k))) == 6
%         rmresearchprojects.Date(k) = datetime(string(paper.DateRaw(k)),"InputFormat","yyyyMM","Locale","ja_JP");
%     elseif strlength(string(rmresearchprojects.DateRaw(k))) == 8
%         rmresearchprojects.Date(k) = datetime(string(rmresearchprojects.DateRaw(k)),"InputFormat","yyyyMMdd","Locale","ja_JP");
%     else
%         error("Error in date format");
%     end
% 
% end

end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% %% Set up the Import Options and import the data
% opts = spreadsheetImportOptions("NumVariables", 18);
% 
% % Specify sheet and range
% opts.Sheet = sheetName;
% opts.DataRange = "A" + dataLines(1, 1) + ":R" + dataLines(1, 2);
% 
% % Specify column names and types
% opts.VariableNames = ["Institute_JP", "Institute_EN", "FundName_JP", "FundName_EN", "Title_JP", "Title_EN", "From", "To", "Name_JP", "Name_EN", "Budget_all", "Budget_direct", "Budget_indirect", "Permalink", "Abstract_JP", "Abstract_EN", "Type", "MemberType"];
% opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "double", "double", "categorical", "categorical", "double", "double", "double", "string", "string", "string", "double", "double"];
% 
% % Specify variable properties
% opts = setvaropts(opts, ["Institute_JP", "Institute_EN", "FundName_JP", "FundName_EN", "Title_JP", "Title_EN", "Permalink", "Abstract_JP", "Abstract_EN"], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, ["Institute_JP", "Institute_EN", "FundName_JP", "FundName_EN", "Title_JP", "Title_EN", "Name_JP", "Name_EN", "Permalink", "Abstract_JP", "Abstract_EN"], "EmptyFieldRule", "auto");
% 
% % Import the data
% competitiveFund = readtable(workbookFile, opts, "UseExcel", false);
% 
% for idx = 2:size(dataLines, 1)
%     opts.DataRange = "A" + dataLines(idx, 1) + ":R" + dataLines(idx, 2);
%     tb = readtable(workbookFile, opts, "UseExcel", false);
%     competitiveFund = [competitiveFund; tb]; %#ok<AGROW>
% end
% 
% competitiveFund = competitiveFund(~(competitiveFund.Institute_JP==""),:);
% competitiveFund.From = datetime(num2str(competitiveFund.From),'InputFormat','yyyyMMdd');
% competitiveFund.To = datetime(num2str(competitiveFund.To),'InputFormat','yyyyMMdd');
% 
% end