function paper1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  PAPER1 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  PAPER1 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  PAPER1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  paper1 = importfile("G:\My Drive\Research\Documents\CV\経歴\業績\paper.xlsx", "paper", [2, 14]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Apr-2021 13:43:35

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 14];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 24);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":X" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "ISSN", "IDDOI", "IDJGlobalID", "IDNAIDCiNiiID", "IDPMID", "Permalink", "URL", "VarName23", "VarName24"];
opts.VariableTypes = ["string", "string", "string", "string", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "ISSN", "IDDOI", "IDJGlobalID", "IDNAIDCiNiiID", "IDPMID", "Permalink", "URL", "VarName23", "VarName24"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName14", "ISSN", "IDDOI", "IDJGlobalID", "IDNAIDCiNiiID", "IDPMID", "Permalink", "URL", "VarName23", "VarName24"], "EmptyFieldRule", "auto");

% Import the data
paper1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":X" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    paper1 = [paper1; tb]; %#ok<AGROW>
end

end