function rmawards = loadawards(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RMAWARDS = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  RMAWARDS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  rmawards = importfile("data\rm_awards.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2023/01/09 11:44:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 20, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "ID", "AwardName_JP", "AwardName_EN", "Name_JP", "Name_EN", "VarName9", "VarName10", "Institute_JP", "Institute_EN", "VarName13", "VarName14", "DateRaw", "Type", "Country", "URL", "VarName19", "VarName20"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "string", "string", "string", "string", "string", "string", "string", "categorical", "categorical", "string", "string", "double", "categorical", "categorical", "string", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ID", "AwardName_JP", "AwardName_EN", "VarName9", "VarName10", "VarName13", "VarName14", "URL"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName1", "VarName2", "VarName3", "ID", "AwardName_JP", "AwardName_EN", "Name_JP", "Name_EN", "VarName9", "VarName10", "Institute_JP", "Institute_EN", "VarName13", "VarName14", "Type", "Country", "URL", "VarName19", "VarName20"], "EmptyFieldRule", "auto");

% Import the data
rmawards = readtable(filename, opts);

for k = 1:size(rmawards,1)
    if strlength(string(rmawards.DateRaw(k))) == 4
        rmawards.Date(k) = datetime(string(rmawards.DateRaw(k)),"InputFormat","yyyy","Locale","ja_JP");
    elseif strlength(string(rmawards.DateRaw(k))) == 6
        rmawards.Date(k) = datetime(string(paper.DateRaw(k)),"InputFormat","yyyyMM","Locale","ja_JP");
    elseif strlength(string(rmawards.DateRaw(k))) == 8
        rmawards.Date(k) = datetime(string(rmawards.DateRaw(k)),"InputFormat","yyyyMMdd","Locale","ja_JP");
    else
        error("Error in date format");
    end

end


% end
% %% Input handling
% 
% % If no sheet is specified, read first sheet
% if nargin == 1 || isempty(sheetName)
%     sheetName = 1;
% end
% 
% % If row start and end points are not specified, define defaults
% if nargin <= 2
%     dataLines = [2, 1000];
% end
% 
% %% Set up the Import Options and import the data
% opts = spreadsheetImportOptions("NumVariables", 14);
% 
% % Specify sheet and range
% opts.Sheet = sheetName;
% opts.DataRange = "A" + dataLines(1, 1) + ":N" + dataLines(1, 2);
% 
% % Specify column names and types
% opts.VariableNames = ["Date", "Institute_JP", "Institute_EN", "AwardName_JP", "AwardName_EN", "Title_JP", "Title_EN", "Name_JP", "Name_EN", "Type", "Country_JP", "Country_EN", "VarName13", "VarName14"];
% opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "string", "string", "string", "double", "string", "string", "string", "string"];
% 
% % Specify variable properties
% opts = setvaropts(opts, ["AwardName_JP", "AwardName_EN", "Title_JP", "Title_EN", "VarName13", "VarName14"], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, ["Institute_JP", "Institute_EN", "AwardName_JP", "AwardName_EN", "Title_JP", "Title_EN", "Name_JP", "Name_EN", "Country_JP", "Country_EN", "VarName13", "VarName14"], "EmptyFieldRule", "auto");
% 
% % Import the data
% prize1 = readtable(workbookFile, opts, "UseExcel", false);
% 
% for idx = 2:size(dataLines, 1)
%     opts.DataRange = "A" + dataLines(idx, 1) + ":N" + dataLines(idx, 2);
%     tb = readtable(workbookFile, opts, "UseExcel", false);
%     prize1 = [prize1; tb]; %#ok<AGROW>
% end
% 
% prize1 = prize1(~isnan(prize1.Date),:);
% prize1.Date = datetime(num2str(prize1.Date),'InputFormat','yyyyMMdd');
% 
% end