function prize1 = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  PRIZE1 = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  PRIZE1 = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  PRIZE1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  prize1 = importfile("prize.xlsx", "prize", [2, 24]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Apr-2021 16:17:11

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 1000];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":N" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Date", "Institute_JP", "Institute_EN", "PrizeName_JP", "PrizeName_EN", "Title_JP", "Title_EN", "Name_JP", "Name_EN", "Type", "Country_JP", "Country_EN", "VarName13", "VarName14"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "string", "string", "string", "double", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["PrizeName_JP", "PrizeName_EN", "Title_JP", "Title_EN", "VarName13", "VarName14"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Institute_JP", "Institute_EN", "PrizeName_JP", "PrizeName_EN", "Title_JP", "Title_EN", "Name_JP", "Name_EN", "Country_JP", "Country_EN", "VarName13", "VarName14"], "EmptyFieldRule", "auto");

% Import the data
prize1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":N" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    prize1 = [prize1; tb]; %#ok<AGROW>
end

prize1 = prize1(~isnan(prize1.Date),:);
prize1.Date = datetime(num2str(prize1.Date),'InputFormat','yyyyMMdd');

end